### ISSUE TITLE
Ballerina client generation from swagger is not working properly

### ISSUE THREAD

**Issue by anuruddhal** [ballerina-platform/ballerina-openapi#111]
**Description:**
- Generating a ballerina client and schema from swagger is not working properly.
- This is due to the following reasons:
 1. Ballerina keywords in the swagger definition are not handled properly (scope,error,continue, version).
 2. Special characters such as `-` in the variable names are not handled properly.
 3. Cyclic dependencies between swagger object are not handled.

**Steps to reproduce:**
1. Generate the ballerina swagger client from this valid swagger file.
https://drive.google.com/open?id=13wJSFTGDml96ETDHIyRTiz3h0R3ziXls
```bash
ballerina swagger client swagger.json
```
2. Try to compile the generated client and stub.

**Affected Versions:**
0.980.1

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by lnash94** [comment]
This issue can be closed due to this for the previous version of the OpenAPI tool and newly client improvements are  included with this PR [https://github.com/ballerina-platform/ballerina-openapi/pull/193](https://github.com/ballerina-platform/ballerina-openapi/pull/193)
