### ISSUE TITLE
Option taken for a service name in the command

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-openapi#141]
In the help text, the following are specified:
```
 (--service-name) <service-name>
            This use for allocating specific user-given name to generated service and client stub according to openapi
            contract. This option uses with the command of openApi to ballerina file generation.


        (-s| --service ) <current-service-name>
            This service name is used to identify the service that need to documented as openApi specification. This
            option uses with the command of ballerina to openApi specification generation.
```
But since there isn't a service name in the new services design, do these make sense anymore? Tried the `--service-name` option and the only difference it seem to make is that now the file name was `foo-service.bal` instead of `petstore-service.bal`.

**Comment by lnash94** [comment]
Related issues [https://github.com/ballerina-platform/ballerina-dev-website/issues/2029](https://github.com/ballerina-platform/ballerina-dev-website/issues/2029)

**Comment by lnash94** [comment]
Close in favour of https://github.com/ballerina-platform/ballerina-dev-website/pull/2142
