### ISSUE TITLE
[Bal -> OpenAPI] --service flag is not working.

### ISSUE THREAD

**Issue by xlight05** [ballerina-platform/ballerina-openapi#146]
**Description:**
In ballerina to OpenAPI generator tool --service flag is not working. However tool works just fine without the flag.

**Steps to reproduce:**
Copy the following content to test.bal file.
```ballerina
import ballerina/http;
import ballerina/log;
listener http:Listener helloEp = new (9090);
service /hello on helloEp {
    resource function get hi(http:Caller caller, http:Request request) {
        http:Response res = new;
        res.setPayload("Hello World!");
        var result = caller->respond(res);
        if (result is error) {
           log:printError("Error when responding", 'error = result);
        }
    }
}
```
Execute the following command 
`bal openapi -i test.bal --service hello`

Command outputs following message
`error: No Ballerina services found with name 'hello' to generate an OpenAPI specification.`

**Affected Product Version:**
slalpha3

**OS, DB, other environment details and versions:**    
Ubuntu 20.04

**Comment by lnash94** [comment]
This `--service` flag is working when the service name with `/` ex: `bal openapi -i test.bal --service /hello`. because it gives the service name as its `absoluteResourcePath` with `/hello`.
