### ISSUE TITLE
WSO2 copyright notice gets added to generated sources

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-openapi#330]
It seems we are now adding a WSO2 copyright notice to sources generated by the OpenAPI tool. This is problematic for the regular user. It's better if this can be made configurable. 
e.g., provide a flag to provide a copyright profile: `--copyright=/path/to/copyright/notice` in the OpenAPI CLI command

**Comment by indikasampath2000** [comment]
Ack. We'll change the OpenAPI tool to support this.

**Comment by hevayo** [comment]
Instead of --copyright we can have a generic name ie --prefix

**Comment by indikasampath2000** [comment]
@pubudu91, we have removed the copyright adding into the generated code https://github.com/ballerina-platform/ballerina-openapi/pull/331. We will provide better option by https://github.com/ballerina-platform/ballerina-openapi/issues/333
