### ISSUE TITLE
Adding a new command line option to add the copyright to the generated file

### ISSUE THREAD

**Issue by lnash94** [ballerina-platform/ballerina-openapi#333]
**Description:**
As suggested with this issue [https://github.com/ballerina-platform/ballerina-openapi/issues/330](https://github.com/ballerina-platform/ballerina-openapi/issues/330) will add the option to a ballerina to openapi command to generate a file with given copyright profile. 
suggested improvement 
`bal openapi -i openapi.yaml --prefix=/path/to/copyright/notice`

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by aneeshafedo** [comment]
Updated suggested improvement
`bal openapi -i openapi.yaml --license license.txt`

**Comment by indikasampath2000** [comment]
The proper command-line argument name is `--license` because we have to be specific about the arguments. The argument `--prefix` would be too broader, and the user will confuse what sort of prefix is about i.e. prefix to the variable name, a prefix to the function name, etc.
