### ISSUE TITLE
Add support for json type request body

### ISSUE THREAD

**Issue by kasthuriraajan** [ballerina-platform/ballerina-openapi#404]
**Description:**
OpenAPI tool supports for `json` type `response body` but not supported for `json` type `request body` . Because of this there is a misbehavior in method signature and indentation problem during connector generation time.

The support for `json` type `request body` need to be added to the Open API tool.  

**Suggested Labels:**
Improvement

**Suggested Assignees:**
@aneeshafedo 

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by aneeshafedo** [comment]
This feature is already supported if you define the request as below.

```
      requestBody:
        content:
          application/json:
            schema: {}
        required: true
```

**Generated code**  
```
    remote isolated function createNewRepository(string repoSlug, string workspace, Repository payload) returns Repository|error 
   {
        string  path = string `/repositories/${workspace}/${repoSlug}`;
        http:Request request = new;
        json jsonBody = check payload.cloneWithType(json);
        request.setPayload(jsonBody);
        Repository response = check self.clientEp->post(path, request, targetType=Repository);
        return response;
    }
```
However above generated code contains below unnecessary line.
` json jsonBody = check payload.cloneWithType(json);`
