### ISSUE TITLE
Mapping support for http `default` method in Ballerina to OpenAPI command

### ISSUE THREAD

**Issue by lnash94** [ballerina-platform/ballerina-openapi#557]
**Description:**
Subject

**Describe your problem(s)**

**Describe your solution(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by shafreenAnfar** [comment]
I think we don't need to map `default`. We can simply skip the entire resource with a `warning` error.
