### ISSUE TITLE
Map OAS response when ballerina resource has `http:Response` return type

### ISSUE THREAD

**Issue by lnash94** [ballerina-platform/ballerina-openapi#642]
**Description:**
```ballerina
service / on new http:Listener(9090) {
    resource function get passthrough() returns http:Response|error? {
         ...
        return response;
    }
}
```
**Describe your problem(s)**
The problem is it is questionable to a data type that should map in OAS since `http:Response` is supertype of response

**Describe your solution(s)**

**Comment by shafreenAnfar** [comment]
I think in the case of `http:Response` we don't need to do the mapping. We can just skip the entire resource with a `warning` error.
