### ISSUE TITLE
openapi inheritance

### ISSUE THREAD

**Issue by scivray47** [ballerina-platform/ballerina-openapi#96]
**Description:**
Related to openapi. It seems like the inheritance isn't well handled.
When generating service for an openapi file that contains an inherited schema, got the following message : 

> Encountered an unsupported type. Type `any` would be used for the field.

**Steps to reproduce:**
Consider the following openapi file : 
```
openapi: 3.0.1
info:
  title: test inheritance
  description: test inheritance
  version: 1.0.0
servers:
- url: http://localhost/api/v1
components:
  schemas:
    GuineaPig:
      type: object
      properties:
        property_one:
          type: string
    SuperGuineaPig:
      allOf:
      - $ref: '#/components/schemas/GuineaPig'
      - type: object
        properties:
          property_two:
            type: string
paths:
  /test:
    get:
      operationId: testGuineaPig
      responses:
        '200':
          description: test
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SuperGuineaPig"
```
The ballerina openapi gen-service command output the following message : 

>  Encountered an unsupported type. Type `any` would be used for the field.

and the produced schema is the following : 
```

type GuineaPig record { 
     string 'property\_one;
};
type SuperGuineaPig record { 
    *GuineaPig;
     string 'property\_two;
};
```
**Affected Versions:**
jBallerina 1.2.2
Language specification 2020R1
Ballerina tool 0.8.5

**OS, DB, other environment details and versions:**
Ubuntu 18.04.4 LTS
**Related Issues (optional):**

**Suggested Labels (optional):**

Component/ToolSwagger
**Suggested Assignees (optional):**

**Comment by lnash94** [comment]
Hi @scivray47 ,

Inheritance is a mechanism in which one object acquires all the properties and behaviours of a parent object.
and inheritance concept in openAPI is
 ```In your API, you may have model schemas that share common properties. Instead of describing these properties for each schema repeatedly, you can describe the schemas as a composition of the common property set and schema-specific properties. In OpenAPI version 3, you do this with the allOf keyword``` [Reference for the openAPI specification 
](https://swagger.io/docs/specification/data-models/inheritance-and-polymorphism/#:~:text=In%20your%20API%2C%20you%20may%20have%20model%20schemas%20that%20share%20common%20properties.%20Instead%20of%20describing%20these%20properties%20for%20each%20schema%20repeatedly%2C%20you%20can%20describe%20the%20schemas%20as%20a%20composition%20of%20the%20common%20property%20set%20and%20schema-specific%20properties.%20In%20OpenAPI%20version%203%2C%20you%20do%20this%20with%20the%20allOf%20keyword%3A)

In the above scenario, `GuineaPig` is a parent schema and `SuperGuineaPig` is a subschema extend from the parent. Above API model `GuineaPig`schema share common properties with `SuperGuineaPig`. Composition of the common property set attached to subschema using  `allOf` keyword. 

When comes to map this scenario in Ballerina language it maps to type inclusion of the Object type reference, here it represents that  `SuperGuineaPig` includes all the properties related to `GuineaPig` record.
 According to the two specification above generated code is correct and current, we added improvements to map `any` data type when the schema type is absent.

**Comment by lnash94** [comment]
Close this issue since the `allOf` concept correctly handles in the tool. Please feel free to reopen the issue if you have any concerns regarding the concept. 
Thank you so much for your input :)

**Comment by lnash94** [comment]
Close this issue since the `allOf` concept correctly handles in the tool. Please feel free to reopen the issue if you have any concerns regarding the concept. 
Thank you so much for your input :)
