### ISSUE TITLE
ballerina openapi gen-service fails 

### ISSUE THREAD

**Issue by SimonJ0ngsma** [ballerina-platform/ballerina-openapi#99]
**Description:**
When trying to generate a mock service from a particular yaml file, ballerina fails

**Related Issues (optional):**
None known

**Suggested Labels (optional):**
openapi gen-service

**Suggested Assignees (optional):**
[ballerina-internal.log](https://github.com/ballerina-platform/ballerina-lang/files/4060018/ballerina-internal.log)

[result.zip](https://github.com/ballerina-platform/ballerina-lang/files/4060034/result.zip)

**Comment by lnash94** [comment]
Hi @SimonJ0ngsma 

I checked the given yaml contract with Ballerina Swan Lake Beta versions. Command for service generation in Swan Lake `bal openapi -i result.yaml --mode service` . 
Given `result.yaml` contract has OpenAPI parser issues , Could you please check them, here is the list of parser issue that contains in yaml file. 
[OpenAPI_parser_issue.txt](https://github.com/ballerina-platform/ballerina-openapi/files/7264139/OpenAPI_parser_issue.txt)

Thank you  for you input :)

**Comment by lnash94** [comment]
closing the issue since the root cause seems to be parser issues in the yaml contract. Feel free to reopen if you will still face issues after running against the valid openAPI contract.
